### ISSUE TITLE
Log Details (ERROR): Unexpected error fetching sensor data

### ISSUE THREAD

**Issue by tarheelz** [Verbalinsurection/next_rocket_launch#5]
Not sure what this means.  (Integration appears to be working.  Running v 1.0.3.)

```
This error originated from a custom integration.

Logger: custom_components.next_rocket_launch.sensor
Source: custom_components/next_rocket_launch/sensor.py:78
Integration: next_rocket_launch (documentation, issues)
First occurred: 9:29:01 AM (1 occurrences)
Last logged: 9:29:01 AM

Unexpected error fetching sensor data: timeout() got an unexpected keyword argument 'loop'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/next_rocket_launch/sensor.py", line 41, in async_update_data
    return await ics_data_provider.ics_update()
  File "/config/custom_components/next_rocket_launch/sensor.py", line 78, in ics_update
    async with async_timeout.timeout(10, loop=self.hass.loop):
TypeError: timeout() got an unexpected keyword argument 'loop'
```

**Comment by Verbalinsurection** [comment]
Thank you for your message and the error detail.
I'm working on it and a fix will be available soon (some hours)
