### ISSUE TITLE
Integration disappeared

### ISSUE THREAD

**Issue by manofpants** [Verbalinsurection/next_rocket_launch#6]
A few days ago, the NRL integration disappeared from my HA. I'm on HAOS 11.2 and in the community folder, the folder in custom_components was gone. I just reinstalled from HACS and getting this:

Logger: homeassistant.loader
Source: loader.py:836
First occurred: 10:23:38 AM (3 occurrences)
Last logged: 10:24:08 AM

Unexpected exception importing platform custom_components.next_rocket_launch.sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 790, in _option
    yield
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 92, in block6
    self._rule_()
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 74, in wrapper
    return self._call(ruleinfo)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 612, in _call
    result = self._recursive_call(ruleinfo)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 643, in _recursive_call
    return self._invoke_rule(ruleinfo, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 689, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 404, in _rule_
    self._expre_()
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 74, in wrapper
    return self._call(ruleinfo)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 612, in _call
    result = self._recursive_call(ruleinfo)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 643, in _recursive_call
    return self._invoke_rule(ruleinfo, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 689, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 488, in _expre_
    self._error(
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 548, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedParse: (6:14) expecting one of: '|' <choice> <element> <option><sequence> :
ALPHADIGIT = ? "[a-zA-Z0-9]";
             ^
expre
rule
grammar
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 233, in parse
    result = rule()
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 74, in wrapper
    return self._call(ruleinfo)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 612, in _call
    result = self._recursive_call(ruleinfo)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 643, in _recursive_call
    return self._invoke_rule(ruleinfo, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 689, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 66, in _start_
    self._grammar_()
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 74, in wrapper
    return self._call(ruleinfo)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 612, in _call
    result = self._recursive_call(ruleinfo)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 643, in _recursive_call
    return self._invoke_rule(ruleinfo, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 689, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 101, in _grammar_
    self._closure(block6)
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 882, in _closure
    block()
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 91, in block6
    with self._option():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 796, in _option
    raise FailedCut(e)
tatsu.exceptions.FailedCut: (6:14) expecting one of: '|' <choice> <element> <option><sequence> :
ALPHADIGIT = ? "[a-zA-Z0-9]";
             ^
expre
rule
grammar
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 836, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 853, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/next_rocket_launch/sensor.py", line 6, in <module>
    from ics import Calendar
  File "/usr/local/lib/python3.11/site-packages/ics/__init__.py", line 3, in <module>
    from .alarm import AudioAlarm, DisplayAlarm
  File "/usr/local/lib/python3.11/site-packages/ics/alarm/__init__.py", line 1, in <module>
    from ics.alarm.audio import AudioAlarm
  File "/usr/local/lib/python3.11/site-packages/ics/alarm/audio.py", line 3, in <module>
    from ics.alarm.base import BaseAlarm
  File "/usr/local/lib/python3.11/site-packages/ics/alarm/base.py", line 6, in <module>
    from ics.component import Component
  File "/usr/local/lib/python3.11/site-packages/ics/component.py", line 5, in <module>
    from ics.grammar.parse import Container
  File "/usr/local/lib/python3.11/site-packages/ics/grammar/parse.py", line 10, in <module>
    GRAMMAR = tatsu.compile(fd.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/tool.py", line 165, in compile
    model = cache[key] = gen.parse(grammar, config=config, **settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 237, in parse
    raise self._furthest_exception
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 790, in _option
    yield
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 1173, in _regex_
    self._STRING_()
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 74, in wrapper
    return self._call(ruleinfo)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 612, in _call
    result = self._recursive_call(ruleinfo)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 643, in _recursive_call
    return self._invoke_rule(ruleinfo, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 689, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.11/site-packages/tatsu/bootstrap.py", line 1110, in _STRING_
    self._error(
  File "/usr/local/lib/python3.11/site-packages/tatsu/contexts.py", line 548, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedParse: (6:15) expecting one of: "((?:[^"\n]|\"|\\)*?)"'((?:[^'\n]|\'|\\)*?)' :
ALPHADIGIT = ? "[a-zA-Z0-9]";
              ^
STRING
regex
regexes
pattern
separator
gather
term
element
sequence
option
choice
expre
rule
grammar
start

**Comment by manofpants** [comment]
FYI the declaration is still in my yaml where it had been for at least a year.

**Comment by Verbalinsurection** [comment]
Thank you for this informations, I will check on it

**Comment by Verbalinsurection** [comment]
Problem found : ICS library need update for problem with Tatsu
Changing to user newer version of ICS (0.7.2)
Publication to HACS in progress
